services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    autoDeploy: true
    branch: main
