"""
Import Content from Claude Script
Import new or improved content (generated by Claude) into your Turso database
"""

import sys
import os
from pathlib import Path
import json
import argparse
from typing import Dict, Any, List

# Add parent directory to path
backend_path = Path(__file__).parent.parent
sys.path.insert(0, str(backend_path))

from dotenv import load_dotenv

load_dotenv()

try:
    import libsql
    from app.config import get_settings
except ImportError as e:
    print(f"❌ Error importing modules: {e}")
    sys.exit(1)


def get_db_connection():
    """Get Turso database connection"""
    settings = get_settings()

    if not settings.has_turso:
        print("❌ Turso database not configured")
        print("Please set TURSO_DATABASE_URL and TURSO_AUTH_TOKEN in .env")
        sys.exit(1)

    try:
        client = libsql.connect(
            database=settings.turso_database_url, auth_token=settings.turso_auth_token
        )
        return client
    except Exception as e:
        print(f"❌ Cannot connect to Turso database: {e}")
        sys.exit(1)


def import_project(client, data: Dict[str, Any], dry_run: bool = False):
    """Import a new project"""
    required_fields = ["id", "title", "github_url", "star", "technologies"]
    missing = [f for f in required_fields if f not in data]

    if missing:
        print(f"❌ Missing required fields: {', '.join(missing)}")
        return False

    # Validate STAR fields
    star_fields = ["situation", "task", "action", "result", "impact", "architecture"]
    missing_star = [f for f in star_fields if f not in data["star"]]
    if missing_star:
        print(f"❌ Missing STAR fields: {', '.join(missing_star)}")
        return False

    if dry_run:
        print(f"✅ [DRY RUN] Would add project: {data['title']}")
        return True

    try:
        # Insert project
        client.execute(
            """INSERT OR REPLACE INTO projects 
               (id, title, github_url, star_situation, star_task, star_action,
                star_result, star_impact, star_architecture, featured)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                data["id"],
                data["title"],
                data["github_url"],
                data["star"]["situation"],
                data["star"]["task"],
                data["star"]["action"],
                data["star"]["result"],
                data["star"]["impact"],
                data["star"]["architecture"],
                1 if data.get("featured", False) else 0,
            ),
        )

        # Clear and insert technologies
        client.execute(
            "DELETE FROM project_technologies WHERE project_id = ?", (data["id"],)
        )
        for tech in data["technologies"]:
            client.execute(
                "INSERT INTO project_technologies (project_id, technology) VALUES (?, ?)",
                (data["id"], tech),
            )

        client.commit()
        print(f"✅ Added project: {data['title']}")
        return True

    except Exception as e:
        print(f"❌ Error adding project: {e}")
        return False


def import_experience(client, data: Dict[str, Any], dry_run: bool = False):
    """Import a new work experience"""
    required_fields = [
        "id",
        "role",
        "company",
        "duration",
        "location",
        "star",
        "technologies",
    ]
    missing = [f for f in required_fields if f not in data]

    if missing:
        print(f"❌ Missing required fields: {', '.join(missing)}")
        return False

    if dry_run:
        print(f"✅ [DRY RUN] Would add experience: {data['role']} at {data['company']}")
        return True

    try:
        # Insert experience
        client.execute(
            """INSERT OR REPLACE INTO experience 
               (id, role, company, duration, location, star_situation, star_task,
                star_action, star_result, star_impact, star_architecture)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                data["id"],
                data["role"],
                data["company"],
                data["duration"],
                data["location"],
                data["star"]["situation"],
                data["star"]["task"],
                data["star"]["action"],
                data["star"]["result"],
                data["star"]["impact"],
                data["star"]["architecture"],
            ),
        )

        # Clear and insert technologies
        client.execute(
            "DELETE FROM experience_technologies WHERE experience_id = ?", (data["id"],)
        )
        for tech in data["technologies"]:
            client.execute(
                "INSERT INTO experience_technologies (experience_id, technology) VALUES (?, ?)",
                (data["id"], tech),
            )

        # Insert competencies if provided
        if "competencies" in data:
            client.execute(
                "DELETE FROM experience_competencies WHERE experience_id = ?",
                (data["id"],),
            )
            for comp in data["competencies"]:
                client.execute(
                    "INSERT INTO experience_competencies (experience_id, competency) VALUES (?, ?)",
                    (data["id"], comp),
                )

        # Insert soft skills if provided
        if "soft_skills" in data:
            client.execute(
                "DELETE FROM experience_soft_skills WHERE experience_id = ?",
                (data["id"],),
            )
            for skill in data["soft_skills"]:
                client.execute(
                    "INSERT INTO experience_soft_skills (experience_id, soft_skill) VALUES (?, ?)",
                    (data["id"], skill),
                )

        client.commit()
        print(f"✅ Added experience: {data['role']} at {data['company']}")
        return True

    except Exception as e:
        print(f"❌ Error adding experience: {e}")
        return False


def import_publication(client, data: Dict[str, Any], dry_run: bool = False):
    """Import a new publication"""
    required_fields = ["id", "title", "outlet", "date"]
    missing = [f for f in required_fields if f not in data]

    if missing:
        print(f"❌ Missing required fields: {', '.join(missing)}")
        return False

    if dry_run:
        print(f"✅ [DRY RUN] Would add publication: {data['title']}")
        return True

    try:
        client.execute(
            """INSERT OR REPLACE INTO publications 
               (id, title, outlet, date, related_project_id)
               VALUES (?, ?, ?, ?, ?)""",
            (
                data["id"],
                data["title"],
                data["outlet"],
                data["date"],
                data.get("related_project_id"),
            ),
        )

        client.commit()
        print(f"✅ Added publication: {data['title']}")
        return True

    except Exception as e:
        print(f"❌ Error adding publication: {e}")
        return False


def update_profile_summary(client, summary: str, dry_run: bool = False):
    """Update profile summary"""
    if dry_run:
        print(f"✅ [DRY RUN] Would update profile summary")
        print(f"   New summary: {summary[:100]}...")
        return True

    try:
        client.execute(
            "UPDATE profile SET summary = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1",
            (summary,),
        )
        client.commit()
        print(f"✅ Updated profile summary")
        return True
    except Exception as e:
        print(f"❌ Error updating profile: {e}")
        return False


def import_activity(client, data: Dict[str, Any], dry_run: bool = False):
    """Import a new activity"""
    required_fields = ["time", "category", "title", "description", "type"]
    missing = [f for f in required_fields if f not in data]

    if missing:
        print(f"❌ Missing required fields: {', '.join(missing)}")
        return False

    # Validate category and type
    valid_categories = ["GitHub", "ArXiv", "Course", "Deploy", "Research", "Learning"]
    valid_types = ["milestone", "research", "learning", "past"]

    if data["category"] not in valid_categories:
        print(f"❌ Invalid category. Must be one of: {', '.join(valid_categories)}")
        return False

    if data["type"] not in valid_types:
        print(f"❌ Invalid type. Must be one of: {', '.join(valid_types)}")
        return False

    if dry_run:
        print(f"✅ [DRY RUN] Would add activity: {data['title']}")
        return True

    try:
        client.execute(
            """INSERT INTO activities (time, category, title, description, type)
               VALUES (?, ?, ?, ?, ?)""",
            (
                data["time"],
                data["category"],
                data["title"],
                data["description"],
                data["type"],
            ),
        )
        client.commit()
        print(f"✅ Added activity: {data['title']}")
        return True
    except Exception as e:
        print(f"❌ Error adding activity: {e}")
        return False


def main():
    """Main function"""
    parser = argparse.ArgumentParser(
        description="Import Claude-improved content into your Turso database"
    )
    parser.add_argument("file", help="JSON file containing the content to import")
    parser.add_argument(
        "--type",
        choices=["project", "experience", "publication", "activity", "profile-summary"],
        help="Type of content to import (auto-detected if not specified)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview changes without making them"
    )
    parser.add_argument(
        "--force", action="store_true", help="Skip confirmation prompts"
    )

    args = parser.parse_args()

    # Load JSON file
    try:
        with open(args.file, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"❌ File not found: {args.file}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Invalid JSON: {e}")
        sys.exit(1)

    # Connect to database
    client = get_db_connection()

    print("\n🎯 Import Content to Turso Database")
    print(f"📄 File: {args.file}")

    # Auto-detect type if not specified
    content_type = args.type
    if not content_type:
        if isinstance(data, str):
            content_type = "profile-summary"
        elif "time" in data and "category" in data and "type" in data:
            content_type = "activity"
        elif "role" in data and "company" in data:
            content_type = "experience"
        elif "github_url" in data:
            content_type = "project"
        elif "outlet" in data:
            content_type = "publication"
        else:
            print("❌ Cannot auto-detect content type. Please specify --type")
            sys.exit(1)
        print(f"🔍 Auto-detected type: {content_type}")

    # Show preview
    if not args.dry_run and not args.force:
        print("\n📋 Preview:")
        print(json.dumps(data, indent=2))
        response = input("\n❓ Proceed with import? (y/N): ")
        if response.lower() != "y":
            print("❌ Import cancelled")
            return

    # Import based on type
    success = False
    if content_type == "project":
        success = import_project(client, data, args.dry_run)
    elif content_type == "experience":
        success = import_experience(client, data, args.dry_run)
    elif content_type == "publication":
        success = import_publication(client, data, args.dry_run)
    elif content_type == "activity":
        success = import_activity(client, data, args.dry_run)
    elif content_type == "profile-summary":
        if isinstance(data, dict) and "summary" in data:
            success = update_profile_summary(client, data["summary"], args.dry_run)
        elif isinstance(data, str):
            success = update_profile_summary(client, data, args.dry_run)
        else:
            print("❌ Invalid format for profile summary")

    if success:
        print("\n✅ Import completed successfully!")
        if not args.dry_run:
            print("\n📊 Verify changes:")
            print(
                f"   python scripts/view_portfolio.py {content_type.replace('-', '_')}"
            )
    else:
        print("\n❌ Import failed")
        sys.exit(1)


if __name__ == "__main__":
    main()
